// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DaterangepickerController from "./daterangepicker_controller"
application.register("daterangepicker", DaterangepickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OnewayReturnController from "./oneway_return_controller"
application.register("oneway-return", OnewayReturnController)

import ScreenfullController from "./screenfull_controller"
application.register("screenfull", ScreenfullController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SlimController from "./slim_controller"
application.register("slim", SlimController)
